spring:
  application:
    name: starlet-academy
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: 'update'
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
server:
  port: 8086
api:
  props:
    api-username: starlet
    api-password: starlet
logging:
  level:
    org:
      hibernate:
        SQL: debug

