spring:
  application:
    name: starlet-academy
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root1234
  jpa:
    hibernate:
      ddl-auto: 'update'
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: false
#      type: trace
server:
  port: 8080
api:
  props:
    api-username: starlet
    api-password: starlet
#schedule:
#  cron: "30 * * * * ?"
#logging:
#  level:
#    org:
#      hibernate:
##        SQL: debug
#      springframework:
#        web: debug

